### ISSUE TITLE
Vertically centering dropdown items

### ISSUE THREAD

**Issue by ench0** [joo6077/cool_dropdown#11]
First thanks for this module, it completely replaced my other dropdown solutions.

It has LOADS of options so it is somewhat easy to get lost :-). I would like to be able to center my dropdown options so the selected item comes in the middle center of the dropdown.

I guess it is easier to explain it via the screenshot:

![image](https://user-images.githubusercontent.com/10009972/201357582-f65c9956-263c-4125-bf52-0fea909ef2ca.png)

Dropdown has 10 options, from 1 to 10. It only shows 5 items at the time (controlled via height option). 

I would like for the currently selected item ('5' in this case) to be in the middle of the displayed list rather than at the top. I tried all the 'align' option in the module, but no luck. Is there an option there or something else that I'm missing?

Many thanks!

**Comment by joo6077** [comment]
Sorry it's too late to update your requested feature but I update v2.1.0 selectedItemAlign in dropdown options.
