### ISSUE TITLE
could there be an option make the dropdown height adapt to height of items it receives?

### ISSUE THREAD

**Issue by Ckm54** [joo6077/cool_dropdown#12]
I have a list of currently about 5 items and there is alot of space left blank. I would like it to adapt to the available items and when i add more it increases to a maximum of say 10 whereby i can then scroll

**Comment by joo6077** [comment]
There is no ways to adapt height fit to items heights. Do you have any screenshots?

**Comment by Ckm54** [comment]
![Screenshot from 2022-12-09 09-16-45](https://user-images.githubusercontent.com/39172663/206637478-f8d39a92-1ad6-438d-9b55-cce87c61d3ca.png)
i would like it to get rid of the extra space below the items instead of me explicitly setting a fixed height, say i adapt it to a certain length of items instead

**Comment by joo6077** [comment]
You can set dropdown height depends on how many items in the list

**Comment by Ckm54** [comment]
I have just set a minimum static height and other items will scroll, closing the issue since that's the solution that has worked on my end, Thanks!
