### ISSUE TITLE
Remove print() method

### ISSUE THREAD

**Issue by LeventeWolf** [joo6077/cool_dropdown#15]
Please remove the following print from line 118.
```
// 기본값 셋팅
if (defaultValue != null) {
  print('.. $defaultValue');
  this.defaultValue = defaultValue;
} else {
  this.defaultValue = {};
}
```

**Comment by joo6077** [comment]
Sure I will remove all print method!
I'm implementing v2 to refactoring old code into new code and improve plugin performance.
