### ISSUE TITLE
Can we show dropdown item mainaxis on results mainaxis when selects ?

### ISSUE THREAD

**Issue by maheshperi19** [joo6077/cool_dropdown#2]
Hi,
Thanks for your package. Its really awesome!!!
When I click on dropdown, again it is showing list with all items with gap between results and dropdown. My requirement is to show entire dropdown need to show in results mainaxis to avoid selected value showing twice. 

For Eg : First time I have selected "Apple". It is showing in results. Now if clicks on dropdown, it is showing all list of items along with "Apple" result. My idea is to show drop down over the result with all items from 0th position irrespective of selected value.

Please find attached screenshots for reference : 

![1](https://user-images.githubusercontent.com/58836654/143297633-5a920ff1-25e7-4647-9597-1dbcdafb9b2b.PNG)
![2](https://user-images.githubusercontent.com/58836654/143297660-0fb56dd5-64e7-4b4b-af9a-86f93d7c28f4.jpeg)

**Comment by joo6077** [comment]
There is "gap" option which is gap between results and dropdown but you can set this property negative as the height of the result. Then, dropdown's 0th position will cover result.

**Comment by maheshperi19** [comment]
Thank you. I will try this.
