### ISSUE TITLE
Is it possible to add scroll bar to the items?

### ISSUE THREAD

**Issue by TimeLord2010** [joo6077/cool_dropdown#8]
I also noticed some possible improvements in typing. If you think this is a good idea, I could make a pull request.

**Comment by joo6077** [comment]
Yeah I think that would be good idea to be improvements! I really appreciate your suggestion but I'm thinking to renew this library from scratch like rebuilding structure of library and add more features after finishing my application.

**Comment by joo6077** [comment]
It's impossible add scroll bars in items

**Comment by joo6077** [comment]
I add marquee option in resultOptions and dropdownItemOptions.
