### ISSUE TITLE
how to use this??? I am using a datatable2 package and..

### ISSUE THREAD

**Issue by fisforfaheem** [joo6077/cool_dropdown#9]
I want to add multiple items'(buttons) and upon clicking on them an action I performed like this:

![image](https://user-images.githubusercontent.com/35878088/190104892-5e21f645-4a33-4f9f-9c05-87b79740ca5c.png)

i want to add add and view buttons to this drop down...but with your package it's not possible or maybe too difficult pleas guide.

**Comment by joo6077** [comment]
It’s possible to make it! You should get rid of resultBD style and then put action button icon instead. One more thing you should do is you should set dropdown gap property negative as icon height and alignment right. I hope it would work!

**Comment by fisforfaheem** [comment]
all i had to do was to add a second item in ths list..it worked thanks
